### ISSUE TITLE
Newa script issues - letter shapes, conjunctions problems

### ISSUE THREAD

**Issue by anandakm** [notofonts/newa#1]
## Defect Report
Initial testing report, issues and suggestions for impovements.

### Title 
  > Newa script issues and suggestions

### Font 
  > Full file name, for example 'NotoSansNewa-Regular.ttf'.

### Where the font came from, and when
  > For example:
  >   Site: https://github.com/googlei18n/noto-fonts-alpha/tree/master/from-pipeline/unhinted/ttf/sans/NotoSansNewa

### Issue
  > The main problem with “Noto Sans Newa” is conjunctions height which actually should fit mostly in baseline.. now almost all 2 letters conjunctions go outside baseline which is making the letters look irregular.. up and downs. 
> Also 3 letter conjunctions have not been taken into consideration. all 3 letters conjunctions are missing. Newa and Ranjana script contains 3 letters conjunctions too. Single letter & conjunctions should try to fit in same baseline.
> 𑐨  भ “Bha” shape is not correct.
> व wa is little odd and wider than letters
> 𑐎 ka shape right arc should be straight one like in other conjuncts with ka
> व wa conjuncts are mistaken with "ba"
> भ “Bha” conjuncts shapes seems odd 
> shape of "ya" is similar to shape of "pa" should be distinguished
> Ha, Dha, Da, Bha, Jha, ya, ka, wa, shape can be improved.
> Rainitial is not rendering properly while typing
  
### Screenshot
![notosans_newa_improvement](https://user-images.githubusercontent.com/39795356/40799293-e9576dda-652c-11e8-994a-9d4888b0200f.jpg)

### Others
We will be testing the font for improvements, Please suggest tools for testing and typing input tools.
Thank you.

**Comment by simoncozens** [comment]
Is this still an issue, or are the issues here now resolved with the new font?

**Comment by punchcutter** [comment]
This was all addressed years ago with input from Ananda, the OP.

**Comment by simoncozens** [comment]
Excellent, thanks!

**Comment by anandakm** [comment]
"Noto Sans Newa" font 1st version was released on Android 9 Pie. Now it's android 12 and we still have same old version 1 font. When shall we expect latest corrected Newa font on Android? Thank you.

**Comment by punchcutter** [comment]
That also should have been updated years ago. Can someone please update Android with newer Noto fonts? Some of them like Newa were totally messed up in the first place and needed lots of fixes. We spent so much time fixing all this and expected it would be updated by now.

**Comment by simoncozens** [comment]
Yes, we are working on this right now. The Android team asked for a list of suggested font updates and I have provided one. M
